### ISSUE TITLE
Build some error

### ISSUE THREAD

**Issue by yangkile** [reveny/Android-Emulator-Detection#6]
The latest version has some missing files, such as Android.mk

i see 

externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Build/Android.mk"
        }
    }

but when git history ,at 2cacdd2893e3eaa6cecac9921863718e55f59206 delete it

**Comment by msdhedhi** [comment]
Seeing the same issue when building the project
3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':emulatordetection:configureNdkBuildDebug[x86_64]'.
> [CXX1400] Gradle project ndkBuild.path is Android-Emulator-Detection/emulatordetection/src/main/jni/Build/Android.mk but that file doesn't exist

**Comment by reveny** [comment]
Somehow git didn't push the build files, will fix.
